### ISSUE TITLE
ALB created when no ports published

### ISSUE THREAD

**Issue by taiidani** [docker/ecs-plugin#156]
In terms of speed, cost savings, etc, is it possible to have an ALB not be created when there are no containers in the docker-compose file that have any ports published?

```yml
version: "3.8"

services:
    app:
        image: taiidani/example:latest
        build: .
        environment:
            ENV: development
```

Seems like $15/month more than it needs to be! 😄
