### ISSUE TITLE
Service doesn't have a com.docker.compose.service tag

### ISSUE THREAD

**Issue by fracturx** [docker/ecs-plugin#158]
I've been trying to find the solution to this issue for 3 hours now and I can't seem to make it work. The example works fine, but when I try to host my own setup, it composes fine with the `docker ecs compose up`, but then when I try to access its ip address using `docker ecs compose ps`it gives this message:

```js
service arn:aws:ecs:us-east-1:885192933549:service/server-BackendService-1RGWIKLFI55RB doesn't have a com.docker.compose.service tag
```

This is my docker-compose.yml:
```yml
version: '3.8'
services:
  frontend:
    restart: always
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-1:{pretend-this-is-my-id}:secret:myname-randomnumbers
    image: fracturx/oceanic:frontend
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    restart: always  
    x-aws-pull_credentials: same as one in frontend
    image: fracturx/oceanic:backend
    ports:
      - '8000:8000'
```

The frontend service's image is a react build made with node 14.5.0 alpine and served using nginx:alpine base image.
Dockerfile (for frontend):
```dockerfile
FROM node:14.5.0-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY src ./src
COPY public ./public
RUN npm run build


FROM nginx:alpine
COPY --from=build /app/build/ /usr/share/nginx/html
COPY web/nginx.conf /etc/nginx/conf.d/default.conf
```
Backend service's image is express api
Dockerfile (for backend):
```dockerfile
FROM node:14.5.0-alpine
WORKDIR /server
COPY package*.json ./
RUN npm install
COPY . ./
EXPOSE 8000
CMD ["npm", "start"]
```
I have made sure to tag and push the latest builds to my private docker hub repo and using the default context and composing locally on my machine works fine.
