### ISSUE TITLE
Unable to use ECR Image

### ISSUE THREAD

**Issue by stevejgordon** [docker/ecs-plugin#173]
I've been trying out the ECS plug-in and run into a couple of issues. The first is that when I specify an ECR image, it doesn't appear to use it or I'm doing something incorrectly.

My docker-compose is as follows...

```
version: '3.8'
services:

  worker-service:
    build:
      context: .
      dockerfile: /EcrWorkerDemo/Dockerfile
    image: {accountid}.dkr.ecr.eu-west-2.amazonaws.com/ecr-demo:latest
```

The resulting Task Definition attempts to use Docker Hub...

```
...
 "stopTimeout": null,
  "image": "docker.io/{accountid}.dkr.ecr.eu-west-2.amazonaws.com/ecr-demo:latest",
  "startTimeout": null,
...
```

Is there anything extra I need to configure to prevent this attempting to pull from docker.io.

As a supplementary question, if I'm using an image which does not need to expose ports (a worker service), can I prevent the creation of the load balancer etc.
