### ISSUE TITLE
The load balancer URL is not shown as part of the `ps` output

### ISSUE THREAD

**Issue by chris-crone** [docker/ecs-plugin#178]
With v1.0.0-beta.2, load balancer URL printing with the `ps` command is broken.

For the Compose file:
```yaml
version: "3.8"

services:
  front:
    image: nginx
    ports:
      - "80:80"
```

The `ps` output is as follows:
```console
ID                                           NAME                REPLICAS            PORTS
loadbalancertest-FrontService-CRD1QZJUUYG3   front               1/1
```

We would expect to see the load balancer URL and port mapping under the `PORTS` column.

The issue has been isolated to [here](https://github.com/docker/ecs-plugin/pull/164/commits/f516af88afdf88f074efadb7c1a854c70ec1d1a0#diff-5e7c7b6de07756aee69dfc48c137c0c4R62-R66) and will be fixed in beta3.

Thanks @aiordache for finding this!
