### ISSUE TITLE
Specifying a VPC-ID for compose up

### ISSUE THREAD

**Issue by thijmenboot** [docker/ecs-plugin#184]
Hello,

I have been trying to connect to a specific VPC using `docker ecs compose up`
I have defined a vpc in my docker-compose.yml in the following way;

```
version: '3.8'
services:
  xxxxx:
    image: xxxx
    container_name: xxxx
    ports:
     - 'xxxx'

x-aws-vpc: "vpc-xxxx" (vpc id)

```

this simply returns that I have not set a default VPC for my account. I have also tried putting the VPC ARN into the field. This returns  

"The vpc ID 'arn:aws::eu-west-1:xxx(account id):vpc/vpc-xxxxx(vpc id)' does not exist" (this seems to be a more logical response when I tried vpc id)

I am not sure if I am doing something wrong or if this is a bug, any help would be appreciated!
