### ISSUE TITLE
Support for sharing named volumes (ephemeral data) across containers.

### ISSUE THREAD

**Issue by ledzeppelin** [docker/ecs-plugin#226]
Thanks so much for the tight feedback loop on addressing bugs and feature requests.

**ecs-plugin** plugin currently doesn't support the use of named volumes to share ephemeral data between containers.  For example when trying to share static content between containers (example from https://stackoverflow.com/a/44284993/784637)

```
services:
  nginx:
    volumes:
      - static-content:/usr/src/app

  web:
    volumes:
      - static-content:/usr/src/app/public

volumes:
  static-content:
```

One would expect a warning:
```
WARN[0000] services.volumes: unsupported attribute
compose file is incompatible with Amazon ECS
```

Would you be able to put this on the roadmap?  Note that this request is different from https://github.com/docker/ecs-plugin/issues/220 since the data is ephemeral and does not need to persist after ` docker ecs compose down`.
