### ISSUE TITLE
Configuring Target Group to Forward 443 to 80

### ISSUE THREAD

**Issue by ajlozier** [docker/ecs-plugin#249]
My initial `docker-compose.yml` file contained an entry for an nginx task, e.g.

```
  webserver:
    x-aws-pull_credentials: "xxxxx"
    image: nginx
    ports:
      - "80:80"
      - "443:443"
```

This causes an additional target group to be created checking the health on port 443. Since I have not configured nginx to accept connections on port 443, nor an installed cert, the health checks of course fail.

What I instead want to do is configure the load balancer to forward connections to port 443 to port 80, which I believe is best practice.

Is there a way to specify this in the `docker-compose.yml` file, or is this currently a manual change I would need to make either directly or using the cloudformation template?

**Comment by ndeloof** [comment]
An initial implementation did supported port forwarding as `443:80`, but as this only applied to external access to services, not service-to-service, this was highly confusing. So we decided **not** to support port translation, and container port is exposed as-is on LoadBalancer. 

If your service only expose port 80, why does your compose file declare port 443?

About HTTPS termination managed by AWS LoadBalancer and forwarded to services as HTTP:80 this is indeed a relevant use-case. Maybe we should introduce a custom extension for this purpose, which would look like:
```yaml
  webserver:
    image: nginx
    x-aws-pull_credentials: "xxxxx"
    ports:
      - target 80
        published: 80
        x-aws-ssl-certificate: ./myserver.crt      
```
