### ISSUE TITLE
Add documentation for how to configure resources for containers

### ISSUE THREAD

**Issue by millarm** [docker/ecs-plugin#251]
I reverse engineered this from looking at the test code, but I suspect many other people will hit the same question:   How do I give my ECS container more RAM/CPU resources?

Looks like it's a block like this

```
services:
  # Backend service
 backend:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 2048M
```
