### ISSUE TITLE
Is there a way to specify what type of balancer (nlb, alb) is used?

### ISSUE THREAD

**Issue by ledzeppelin** [docker/ecs-plugin#252]
Per https://github.com/docker/ecs-plugin/issues/244#issuecomment-680744002, ecs-plugin creates an application load balancer when services use port 80 or 443.

I'm using ports 8080 and 80, and ecs-plugin is spinning up a network load balancer.  Is there a way to specify using an application load balancer instead?

Something like adding `ExtensionUseALB = "x-aws-use_alb"` in https://github.com/docker/ecs-plugin/blob/master/pkg/compose/x.go, then updating https://github.com/docker/ecs-plugin/blob/master/pkg/amazon/backend/cloudformation.go#L289 to check if `project.Extensions[compose.ExtensionUseALB]` is true would be really awesome.

**Comment by ndeloof** [comment]
I had in mind to add into the port spec a protocol declaration:
```yaml
services:
  foo:
    ports:
      - target: 8080
        x-asw-protocol: http
``` 
(could be proposed to the compose spec as an official attribute)

Doing so, we can detect HTTP services not just by 80/443 but also by explicit user declaration for protocol, and I guess this could be useful on other implementations to enable some extra network components / routing capabilities.

**Comment by ndeloof** [comment]
note to myself:
protocol could also be extended to a more detailed form (using OSI model terminology):
```yaml
services:
  foo:
    ports:
      - target: 8080
        protocol: 
          transport: tcp
          application: http
``` 
This would make it easier for docker-compose (relying on plain docker network, which is level 4 only) to select TCP over UDP, without having to maintain an IETF protocols dictionary to guess transport.
