### ISSUE TITLE
Persistence volume data

### ISSUE THREAD

**Issue by shazChaudhry** [docker/ecs-plugin#254]
**What is the problem you're trying to solve**
Allow volume data to be persistent in AWS ECS cluster. For example, I would like to set up a [docker registry](https://hub.docker.com/_/registry) in ECS cluster and I would like images to remain persistent even after ECS cluster is destroyed / recreated

**Describe the solution you'd like**
"[Docker for AWS](https://hub.docker.com/editions/community/docker-ce-aws?tab=description)" had a volume plugin called `Cloudstor` which helped with persisting volume data. 

Below is an extract of a compose file I have used in the past for docker swarm mode in Docker4AWS:

```
version: "3.7"

volumes:
  gitlabPostgresql_data:
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2
      size: 25
      iops: 1000
      backing: relocatable
```

Is it possible to have something similar sort of volume plugin when creating an AWS ECS cluster with docker compose please?
