### ISSUE TITLE
Support for Application Load Balancers

### ISSUE THREAD

**Issue by ay0o** [docker/ecs-plugin#265]
Only network load balancers are supported.

It's quite common to have an application load balancer acting as endpoint forwarding traffic to the target groups based on rules, that is, path-based targeting:

```
/s1 --> target group for s1
/s2 --> target group for s2
```

Right now, even passing an existing pre-configured ALB with `x-aws-loadbalancer` doesn't work, because the `convert` tries to create a TCP  listener which is not suitable for an ALB (only HTTP and HTTPS are supported).

If an ALB is specified and a service exposes a port in the compose file, `docker` should not try to create a listener, just configure the port in the task definition.

Ideally, we could even expand this to have fine-grained control on the ALB and target groups with something like:

`x-aws-loadbalancer-type`: application or network.
`x-aws-loadbalancer`: arn for the application load balancer. If not specified, create one using the type specified by `x-aws-loadbalancer-type`.
`x-aws-alb-rules`: list of rules to attach to the listeners of an ALB.  Required if `x-aws-loadbalancer-type` is application. Not applicable for NLB.
`x-aws-alb-listeners`: list of listeners for the ALB.  Required if `x-aws-loadbalancer-type` is application. Not necessary for NLB as NLB would automatically create a listener for each exposed port (as it's working right now).
`x-aws-loadbalancer-target-groups`:  list of arn of the target groups to attach to the load balancer. Required if `x-aws-loadbalancer-type` is application. If it's network and no target groups are specified, they could be created as they are right now.

And so on.

**Comment by ndeloof** [comment]
path based routing is something we have in mind but doesn't yet have any mapping in Compose model.
We for sure could introduce custom extensions, to support ECS deployment to expose `/s1` and `/s2` as you described on ALB. I then assume some other components of the application do access those path (a client-side web UI probably?). Issue doing so is that such an application then can't be ran locally with docker-compose, breaking the portability of the application model.

**Comment by ay0o** [comment]
You might have:

```
services:
  foo:
    image: "foo"
    ports:
      - 8080:8080

  bar:
    image: "bar"
    ports:
      - 8081:8081
```

Locally, you access them by using the port, http://localhost:8080.

In AWS, you can have an ALB with rules so that:

- https://example.com/foo forwards traffic to a target group attacking the service `foo`
- https://example.com/bar forwards traffic to a target group attacking the service `bar`

The compose is the same, it should not change. What changes is the config of the application. There might be a third service `baz` which uses `foo`:

```
  baz:
    image: "baz"
    environment:
      - FOO_ENDPOINT: "${FOO_ENDPOINT}"
```

And then, if you are running the compose locally, you'd set the variable to `FOO_ENDPOINT=http://localhost:8080`, and if in AWS, `FOO_ENDPOINT=https://example.com/foo`

**Comment by ndeloof** [comment]
An ALB will be created if you use `x-aws-protocol: http` to inform ECS integration the service is actually layer-7 routable.

My concern is exactly about configuring other services so they get the adequate endpoint URL for sibling services. Within compose model, it is expected you can just reach other services on network by service name, without a specific subpath (which only make sense with URL based protocols). We have to find some way to avoid the need for such a manually managed `FOO_ENDPOINT` variable.

Note: the [legacy `links` property](https://docs.docker.com/network/links/) in compose file format do inject such variables in target container, maybe we could leverage this. 
```yaml
services:
  foo:
    image: "foo"
    ports:
      - 8080:8080  

  bar:
    image: "bar"
    links:
      - foo
    ports:
      - 8081:8081
```
doing so, `bar` container has environment variable injected:
- FOO_PORT=tcp://172.17.0.82:8008
- FOO_PORT_8080_TCP_ADDR=172.17.0.82
- FOO_PORT_8080_TCP_PORT=8080
- FOO_PORT_8080_TCP_PROTO=tcp

If we introduce support for application-level protocol declaration in port definition:
```yaml
  foo:
    image: "foo"
    ports:
      - target: 80
        published: 8080
        protocol: tcp,http // actual syntax to be defined
```
... then we could extend this mechanism by setting additional env variable if path-based routing is used:

- ECS deployment:
```
- FOO_PORT=http://172.17.0.82:8008/foo
- FOO_PORT_8080_TCP_PATH=/foo 
```
- local deployment:
```
- FOO_PORT=http://172.17.0.82:8008/
- FOO_PORT_8080_TCP_PATH=/ 
```
